package ru.taskhero.userservice.entity;

/**
 * Коды действий для журнала аудита.
 */
public enum AuditAction {
    USER_CREATED,
    USER_REGISTERED,
    USER_BLOCKED,
    USER_UNBLOCKED,
    USER_ROLE_CHANGED,
    USER_DELETED,
    USER_PASSWORD_RESET,
    PARENT_UPDATED,
    CHILD_CREATED,
    CHILD_UPDATED,
    CHILD_TOKEN_RESET,
    CHILD_EXP_ADJUSTED,
    CHILD_COINS_ADJUSTED,
    CHILD_LEVEL_ADJUSTED,
    TASK_ASSIGNED,
    TASK_APPROVED,
    TASK_REJECTED,
    SHOP_PURCHASE_REQUESTED,
    SHOP_PURCHASE_APPROVED,
    SHOP_PURCHASE_REJECTED,
    MARKETPLACE_ITEM_CREATED,
    MARKETPLACE_ITEM_UPDATED,
    MARKETPLACE_ITEM_DELETED,
    TEMPLATE_LIBRARY_CREATED,
    TEMPLATE_LIBRARY_UPDATED,
    TEMPLATE_LIBRARY_DELETED,
    AVATAR_OPTION_CREATED,
    AVATAR_OPTION_UPDATED,
    AVATAR_OPTION_DELETED,
    BACKGROUND_OPTION_CREATED,
    BACKGROUND_OPTION_UPDATED,
    BACKGROUND_OPTION_DELETED,
    CHILD_AVATAR_FORCED,
    CHILD_BACKGROUND_FORCED
}
