package ru.taskhero.userservice.entity;

/**
 * Коды действий для журнала аудита.
 */
public enum AuditAction {
    USER_CREATED,
    USER_BLOCKED,
    USER_UNBLOCKED,
    USER_ROLE_CHANGED,
    USER_DELETED,
    USER_PASSWORD_RESET,
    PARENT_UPDATED,
    CHILD_UPDATED,
    CHILD_TOKEN_RESET,
    CHILD_EXP_ADJUSTED,
    CHILD_COINS_ADJUSTED,
    CHILD_LEVEL_ADJUSTED,
    MARKETPLACE_ITEM_CREATED,
    MARKETPLACE_ITEM_UPDATED,
    MARKETPLACE_ITEM_DELETED,
    TEMPLATE_LIBRARY_CREATED,
    TEMPLATE_LIBRARY_UPDATED,
    TEMPLATE_LIBRARY_DELETED
}
